### ISSUE TITLE
Can I used this repo with Nexus?

### ISSUE THREAD

**Issue by arvinder06** [bonigarcia/webdrivermanager#1082]
Downloading exe is blocked in our company, and I am wondering if I can host the chromedriver.exe in our company's Nexus repository and use this repository to download from that Nexus?

**Comment by andham** [comment]
I second this. It would be great if it was possible to configure a mirror for each webdriver type. In our case it would be an internal mirror (hosted in Nexus), but I see no reason to limit it to that. It should be possible to specify any mirror URL.
I see that it's possible to configure wdm.useMirror, so maybe this behavior can be extended so that one can specify the URL to use for the mirror?

**Comment by bonigarcia** [comment]
I think you need the use the configuration keys `wdm.chromeDriverUrl`, `wdm.geckoDriverUrl`, etc. This is already available in WebDriverManager. See [doc](https://bonigarcia.dev/webdrivermanager/#advanced-configuration).
