### ISSUE TITLE
119 webdriver to be unavailable

### ISSUE THREAD

**Issue by alexhaoxuan** [bonigarcia/webdrivermanager#1171]
My Chrome version is 119.0.6045.105, and there is no available webdriver version. I am https://googlechromelabs.github.io/chrome-for-testing/#stable Download the beta version here and find that the best version of your version is only version 114, which causes the webdriver to be unavailable

**Comment by Prathapr2** [comment]
Actually the WebDriverManager is not updating Chromedriver for the Chrome browser version 119 and above. Even I'm used the latest release 5.6.2 in pom.XML file in a Maven project.

**Comment by Prathapr2** [comment]
Working fine with WebDriverManager.chromedriver().clearDriverCache().setup();

**Comment by Prathapr2** [comment]
@murkl , try WebDriverManager.chromedriver().clearDriverCache().setup();

**Comment by Prathapr2** [comment]
@murkl No, WeDriverManager supports 119 version, please try WebDriverManager.chromedriver().clearDriverCache().setup(); in some other project or just create a new project and use the same to clear the cache, then you are initial project will fine.

Please see the below,

7.4. Support for chromedriver 115+
The chromedriver team has stopped publishing the chromedriver releases and metadata using their traditional [chromedriver download repository](https://chromedriver.chromium.org/downloads) with chromedriver 114. This way, as of chromedriver 115, the chromedriver releases can only be discovered programmatically using the [Chrome for Testing (CfT) JSON endpoints](https://github.com/GoogleChromeLabs/chrome-for-testing#json-api-endpoints).

This change is very relevant for WebDriverManager, since, as of Chrome 115 and 116, chromedriver cannot be managed automatically by WebDriverManager using the traditional way. Therefore, for older versions of WebDriverManager, this situation led to errors like the following:

io.github.bonigarcia.wdm.online.HttpClient: Error HTTP 404 executing https://chromedriver.storage.googleapis.com/LATEST_RELEASE_116
org.openqa.selenium.SessionNotCreatedException: Could not start a new session. Response code 500. Message: session not created: This version of ChromeDriver only supports Chrome version 114
WebDriverManager 5.4+ implements the support for the CfT endpoints. Therefore, the solution to this problem is to bump WebDriverManager to the latest version (5.6.2 currently). Also, to ensure that the wrong version has not been cached in the resolution cache, you can refresh completely the cache folder (at least once) as follows:

WebDriverManager.chromedriver().clearDriverCache().setup();

**Comment by Chetan11-dev** [comment]
This solution works; it uses the Botasaurus Web Scraping Framework to create Chrome.

## Installation

```bash
pip install botasaurus
```

## Example

```python
from botasaurus import *

driver = bt.create_driver()

driver.get("http://www.python.org")
driver.prompt()
driver.quit()
```

**Comment by Miltonbhowmick** [comment]
When i faced 119 chrome version problem with chrome webdriver, i used stable version from here [https://googlechromelabs.github.io/chrome-for-testing/](url)

**Comment by bonigarcia** [comment]
Please follow the issue template to report issues. In particular, I need to see the WebDriverManager traces to analyze the problem. See more info about how to get these traces [here](https://bonigarcia.dev/webdrivermanager/#troubleshooting).
