### ISSUE TITLE
Try to find driver in Cache if GitHub connection is down

### ISSUE THREAD

**Issue by rtrembleau** [bonigarcia/webdrivermanager#125]
Hi,

First of all, thanks for your work, webdriver manager is today really convenient.
We had an issue today while opening github connection to verify latest geckodriver version (github returned an HTTP 403 error) and a Runtime exception was thrown.

The driver was already in our cache and we expected that webdrivermanager handled this case the following way

- Try to get version from Github 
- On fail => check if a driver exists in cache for the current architecture
- if a driver exists in cache LOG the github access error and warn that we're using the driver in cache
- if there's no driver in cache, throw the RuntimeException as for now.

Don't hesitate to contact me if you need more information.

thanks again.

Romain.

PS : My workaround today is 

`

		BrowserManager firefoxDriverManager = FirefoxDriverManager.getInstance();
		try {
			firefoxDriverManager.setup();
		} catch (Exception  e) {
			firefoxDriverManager.forceCache();
			firefoxDriverManager.setup();
		}
`

**Comment by bonigarcia** [comment]
So far, you force to use the cached version using the `forceCache()` method:

`FirefoxDriverManager().getInstance().forceCache().setup();`

Otherwise wdm tries to find out which is the latest version of the drivers, and for that it must connect to the hosting server:

Moreover, you can override the 403 issue using authenticated requests. Take a look to the [know issues](https://github.com/bonigarcia/webdrivermanager#known-issues)  in the README for more info.

In any case, your proposal (on fail use the cached version, log a warning, etc) could make sense. Let me think about it.

**Comment by rtrembleau** [comment]
Thanks for the quick answer.
I'll try with the known issue recommendations.

**Comment by bonigarcia** [comment]
Solved in version 1.7.0.
