### ISSUE TITLE
WebDriverManger Couldn't get actual chrome driver for Chrome for testing browser. 

### ISSUE THREAD

**Issue by hemanshurana** [bonigarcia/webdrivermanager#1252]
**Description of the problem**: 

WebDriverManger Couldn't get actual chrome driver for Chrome for testing browser. 

**Browser and version**: 

Chrome for test browser version 119 using 

Regular chrome browser installed 122 

**Operating system and architecture**: 

Windows 10 64

**Selenium version**: 

Selenium : 4.12.1

**WebDriverManager version**: 
5.6.4 tried 
5.7.0 tried 

**WebDriverManager call**:  Yes 
```
```

**WebDriverManager traces**: 
```
```

**Error log**: 
WebDriverMangager could not handle this and install/configure chrome driver for Regular browser 122.

org.openqa.selenium.SessionNotCreatedException: Could not start a new session. Response code 500. Message: session not created: This version of ChromeDriver only supports Chrome version 122
Current browser version is 119.0.6045.105 with binary path C:/chrome-test/chrome-win64/chrome.exe 
Host info: host: 1324555', ip: '199.168.0.166'
Build info: version: '4.12.1', revision: '8e34639b11'
System info: os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '11.0.10'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Command: [null, newSession {capabilities=[Capabilities {acceptInsecureCerts: true, browserName: chrome, goog:chromeOptions: {args: [headless, window-size=1920,1080, --disable-extensions, --disable-dev-shm-usage, --remote-allow-origins=*], binary: C:/chrome-test/chrome-win64..., extensions: [], prefs: {download.default_directory: C:\Users\ranahe\NG_Core_Aut..., profile.default_content_setting_values.notifications: 2, profile.default_content_settings.popups: 0}}}]}]
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:140) ~[selenium-remote-driver-4.12.1.jar:?]
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:96) ~[selenium-remote-driver-4.12.1.jar:?]
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:68) ~[selenium-remote-driver-4.12.1.jar:?]
```
```
Selenium can handle this very well

See log...

Mar 08, 2024 12:25:02 PM org.openqa.selenium.devtools.CdpVersionFinder findNearestMatch
WARNING: Unable to find an exact match for CDP version 119, so returning the closest version found: 116

**Comment by bonigarcia** [comment]
Using the latest WebDriverManager version (5.7.0 at the time of this writing) and clearing the cache (at least once) should fix this issue:

```
WebDriverManager.chromedriver().clearDriverCache().setup();
```

If not, please report your WebDriverManager traces. See: https://bonigarcia.dev/webdrivermanager/#troubleshooting
-----

**Comment by tlpbu** [comment]
Hello!
I am using latest WebDriverManager version 5.8.0 and still have similar problem even with suggested fix.
```
org.openqa.selenium.SessionNotCreatedException: Could not start a new session. Response code 500. Message: session not created: This version of ChromeDriver only supports Chrome version 124
Current browser version is 123.0.6312.122 with binary path /Applications/Google Chrome for Testing.app/Contents/MacOS/Google Chrome for Testing 
```

After debugging if is clear version of ChromeDriver is detected based on ordinary Chrome version via shell [command](https://github.com/bonigarcia/webdrivermanager/blob/d56b26de85433c190bf4ba73f9ac7c563bb8e7a8/src/main/resources/commands.properties).
```
➜ /Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome --version
Google Chrome 124.0.6367.61 

~ 
➜ /Applications/Google\ Chrome\ for\ Testing.app/Contents/MacOS/Google\ Chrome\ for\ Testing --version 
Google Chrome for Testing 123.0.6312.122 
```
As a result eventually always latest ChomeDriver is being used and it required manually updating Chrome for Testing but in this case it is even more tricky since there is not compatible version available on https://googlechromelabs.github.io/chrome-for-testing/

Quick solution locally to unblock for me now is to specify `WebDriverManager.chromedriver().clearDriverCache().setup()`.

Big question is if it is correctt by nature detect browser version for chromedriver based on ordinary Chrome if it will be used for Chrome for Testing?
