### ISSUE TITLE
Architecture filter is failing with latest chromedriver version

### ISSUE THREAD

**Issue by JohnGagliardi** [bonigarcia/webdrivermanager#1319]
The latest chromedriver version is '126.0.6478.127'. It looks like the architecture filter on Windows 64 bit is failing because the 32 bit version is being downloaded.

Likely because the chromedriver version has "64" in it.

` 
Architecture.java

  public <T> List<T> filterArm64(List<T> input) {
      if (this != ARM64) {
          return input.stream()
                  .filter(x -> !x.toString().toLowerCase(ROOT)
                          .contains(ARM64.toString().toLowerCase(ROOT))  // I think using contains is the issue here
                          && !ARM64.matchString(x.toString()))
                  .collect(toList());
      }
      return input;
  }
`

**Comment by JohnGagliardi** [comment]
I may be wrong where the issue is in the code.

**Comment by bonigarcia** [comment]
I believe this issue is not valid. I did not see any problem with chromedriver in the latest release of WebDriverManager. If you experience some problem, please use the complete issue template to report any issue. Do not forget any of the template fields (i.e., WebDriverManager version, error traces, WebDriverManager traces, etc.).
