### ISSUE TITLE
Opera driver isn taking LATEST version 

### ISSUE THREAD

**Issue by kovacic100** [bonigarcia/webdrivermanager#134]
Basically this has 2 part problem with Opera.

1. It doesn't take latest version of Opera/Chromium driver, it has to be put implicitly 2.27 instead of "latest"
2. when it download it. It is not set correctly, in zip path operdriver file is added one more folder before.

**Comment by bonigarcia** [comment]
Indeed, there is problem here. The root cause is that the new version of operadriver seems to be [2.27](https://github.com/operasoftware/operachromiumdriver/releases), and this is breaking the semantic versioning style expected by WebDriverManager. I have opened an issue on operachromiumdriver to confirm [whether or not that version number is intentional](https://github.com/operasoftware/operachromiumdriver/issues/38).

In the meantime, there is a workround for WebDriverManager. Run a test with the following twice:

`OperaDriverManager.getInstance().version("2.27").setup();`

The first time the test will fail, but it will run correctly the second and subsequent times.

**Comment by rosolko** [comment]
@bonigarcia Look like they are rethink release versioning after brand new release

**Comment by bonigarcia** [comment]
Solved in version 1.7.0.
