### ISSUE TITLE
CONNECT refused by proxy

### ISSUE THREAD

**Issue by sivasankarb43** [bonigarcia/webdrivermanager#1343]
Description: I have given my proxy correctly still it throwing connection refused, upto yesterday evening its worked fine after that facing this issue.

ERROR i.g.bonigarcia.wdm.WebDriverManager      - There was an error managing chromedriver (latest version) (CONNECT refused by proxy: HTTP/1.1 407 Proxy Authentication Required)
org.apache.hc.client5.http.ClientProtocolException: CONNECT refused by proxy: HTTP/1.1 407 Proxy Authentication Required

Browser and version: chrome version 127

Operating system: Windows 10 64 bit

WebDriverManager version: 5.9.2

WebDriverManager use: wedrivermanager.chromedriver().proxy(proxy).setup();

**Comment by bonigarcia** [comment]
Your proxy seems to be having a connectivity problem. Check the [documentation](https://bonigarcia.dev/webdrivermanager/#advanced-configuration) since it explains how to configure the credentials for your proxy. I mean the methods `proxy(String)` (in which you can include the credentials like `username:password@proxy:port`) or `proxyUser(String)` and `proxyPass(String)`.
