### ISSUE TITLE
Downloading Win64 Firefox driver when Win32 not available

### ISSUE THREAD

**Issue by andrew-sumner** [bonigarcia/webdrivermanager#168]
The latest GeckoDriver (https://github.com/mozilla/geckodriver/releases) had a bug in its build where the Win32 driver was not built.  When wdm.geckoDriverVersion = LATEST and running on a Win32 PC the 0.19.0 Win64 driver is downloaded and setup for use and, as you'd expect, the test suite breaks.

Could you either:
1. throw an error stating that the Win32 driver for the latest version is not available
or
2. use the 0.18.0 version and log a warning that not using the latest

**Comment by bonigarcia** [comment]
It is not clear for me. Is this a bug in WebDriverManager?

**Comment by andrew-sumner** [comment]
Kind of.  Because the 32 bit driver wasn't available in this release of the geckodriver, webdrivermanager downloaded and attempted to run the 64 bt version even though we're running on a 32 bit OS.  

It would probably be nicer to just throw an appropriate error message than attempt to use the 64 bit version which fails with an obsure message.

At the end of the day I was able to work this out eaily enough, and after a bit of googling found out the reason why it wasn't available. However, as I don't know the ability of the people who will be using the framework I'm developing it would be nice to fail with an understandable error.

**Comment by jchaturvedi-cpi** [comment]
If I am using a machine which don't have any browser on it . WebDriverManger is not working. 
Oct 26, 2017 10:31:17 AM org.openqa.selenium.os.UnixProcess checkForError
SEVERE: org.apache.commons.exec.ExecuteException: Execution failed (Exit value: -559038737. Caused by java.io.IOException: Cannot run program "C:\Users\<My Name> \.m2\repository\webdriver\MicrosoftWebDriver\5.16299\MicrosoftWebDriver.exe" (in directory "."): CreateProcess error=193, %1 is not a valid Win32 application)

**Comment by jchaturvedi-cpi** [comment]
Also when I used firefox driver ,its giving me error like , Firefox is not installed your machine.

**Comment by bonigarcia** [comment]
At this moment geckodriver is available both for 32 and 64 bits architectures. In any case, for me it is reasonable that webdrivermanager tries to use the alternative version when one it is not available.
