### ISSUE TITLE
Getting io.github.bonigarcia.wdm.WebDriverManagerException: java.lang.NullPointerException when using v3.0.0

### ISSUE THREAD

**Issue by sayanece2** [bonigarcia/webdrivermanager#260]
Using Maven as a build tool. Its working fine when using v2.2.5. Getting below error when using 3.0.0:

[ERROR] Tests run: 4, Failures: 1, Errors: 0, Skipped: 3, Time elapsed: 4.816 s <<< FAILURE! - in TestSuite
[ERROR] beforeTest(DriverPackage.MainDriver)  Time elapsed: 4.468 s  <<< FAILURE!
io.github.bonigarcia.wdm.WebDriverManagerException: java.lang.NullPointerException
	at DriverPackage.MainDriver.beforeTest(MainDriver.java:27)
Caused by: java.lang.NullPointerException
	at DriverPackage.MainDriver.beforeTest(MainDriver.java:27)

[INFO] 
[INFO] Results:
[INFO] 
[ERROR] Failures: 
[ERROR]   MainDriver.beforeTest:27 » WebDriverManager java.lang.NullPointerException
[INFO] 
[ERROR] Tests run: 4, Failures: 1, Errors: 0, Skipped: 3
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------

Why its throwing null pointer exception in v3.0.0?

Same code runs successfully in v2.2.5.

**Comment by bonigarcia** [comment]
Is this error still happening? Can you share the complete stack trace?

**Comment by sayanece2** [comment]
Yes...this is still happening...attaching the full stack trace
[wdmFullStackTrace.txt](https://github.com/bonigarcia/webdrivermanager/files/2642331/wdmFullStackTrace.txt)

**Comment by pierrepinon** [comment]
Hello @sayanece2, can you provide your code to help you :)

**Comment by bonigarcia** [comment]
@sayanece2 In order to trace the problem, more information is still required, namely:

- Which version of WebDriverManager are you using? In general, latest version is always recommended.
- How are you calling WebDriverManager? (as @pierrepinon asked)

Moreover, from the trace before, I can see you are not using any logging library. In order to get more information from WebDriverManager, it would be nice if you add a logging implementation (e.g. `slf4j-simple`, `logback-classic`, etc.). See more info on #4.

**Comment by bonigarcia** [comment]
WebDriverManager 3.1.0 has been released. Please try the new version. For the shake of traceability, It would be useful if you use a logging library in your project.

**Comment by sayanece2** [comment]
Not sure what was the issue but its working fine with 3.1.0. 
Thanks. :)
