### ISSUE TITLE
Adding Appium to the list of Drivers

### ISSUE THREAD

**Issue by lfarnell** [bonigarcia/webdrivermanager#29]
I've started using your library for a project of mine and was wondering if you would be interest in a pull request for adding Appium drivers to the list.

**Comment by bonigarcia** [comment]
Sure, PR's are welcome!

Please provide JUnit tests with your code in order to assess the new feature. Thank you!

**Comment by bonigarcia** [comment]
Did you manage to add Appium to the driver list?

**Comment by lfarnell** [comment]
@bonigarcia not yet but i'm hopeful to do so in the next little bit

**Comment by rosolko** [comment]
@bonigarcia @lfarnell I use appium for some time. Appium works with own server (like selenium server standalone) and we don't need to store and add some variables to `PATH`. I formed the opinion that we should't implement this type of driver. All of because from site(bitbucket) installs old version of appium server and GUI. And really latest version installs from `node`. From my point of view, the implementation of this functionality useless.

**Comment by bonigarcia** [comment]
I've reviewed Appium and @rosolko has a point.

@lfarnell Could you explain to us what is your idea for supporting Apium in WebDriverManager?

**Comment by bonigarcia** [comment]
As Linus Torvalds said: "_Talk is cheap. Show me the code_".

**Comment by rosolko** [comment]
@lfarnell But on other hand - archive from bitbucket contains installer, not a driver(like chromedriver) that using like a bridge. In this case tool didn't manage webdrivers.

**Comment by bonigarcia** [comment]
This issue seems to be abandoned. Closing.
