### ISSUE TITLE
[Enhancement] Store local copies of wdm.*DriverUrl and resolve them locally

### ISSUE THREAD

**Issue by AlexanderPoleschuk** [bonigarcia/webdrivermanager#293]
Every time WDM goes via _setup -> manage -> filterCandidateUrls -> getDrivers() -> getDriversFromXml_ it grabes drivers via HTTP client to wdm.*DriverUrl, download the xml, parse it and setup a list of urls that are available for download.
It results in WDM is making frequent HTTP requests for the content that doesn't change too often (in other words - browser's drivers are not released each minute/hour/day). 
What do you think about storing these XMLs as a local copies with some expiration time?

Here is how I see it:
1) WDM calls for a specific wdm.*DriverUrl (let's say Chrome).
2) grabs the xml and places it to wdm.targetPath + chromedriver (so for Windows it should be ~/.m2/repository/webdriver/chromedriver). Xml name should be specific to differentiate non-/mirror URLs.
3) Each time getDrivers() is called - WDM primarily checks for local xml and its actuality and depending on result of the check either parse values locally or download a new local version of the XML.

**Comment by pierrepinon** [comment]
@AlexanderPoleschuk can your provide PR for this ?

**Comment by AlexanderPoleschuk** [comment]
@pierrepinon Work is in progress. 
I've made a POC. It still requires some adjustments, but should work for the cases where getDriversFromXml() is called.
The issue is that I randomly receive 403 errors when I ran tests, but I don't want to tune up authenticated requests... So implementation might take some time :)

**Comment by bonigarcia** [comment]
Current version of WebDriverManager uses Java preferences to store persistently the resolved versions of driver binaries. That resolution is linked to a time to live (TTL), i.e. an expiration time. This TTL has a value of 3600 seconds, i.e. 1 hour. As usual, this value can be configured.

All in all, the idea of caching the XML locally is not needed, since required versions (which is the actual value of the XML content). Please don't do a PR about that.
