### ISSUE TITLE
Issue with Jenkins job execution in case of the latest web-briver derived from 73 and save into 74 folder

### ISSUE THREAD

**Issue by agoldenberg01** [bonigarcia/webdrivermanager#320]
HI All:

I have copied web-driver from Chrome 73.0.3683.68 to Chrome 74.0.3729.6 folder and selenium/TestNG suites are pretty feasible in case of running locally on the window image. But Jenkins jobs are failing and give a lot of errors  - remote driver has died, etc... and not working properly. All Jenkins jobs used to work properly before the latest web-driver issue came up and stopped now.
Please, advise.

**Comment by bonigarcia** [comment]
I don't recommend to change driver folder nor binaries. Instead, use latest version of WebDriverManager. See https://github.com/bonigarcia/webdrivermanager/issues/318#issuecomment-472926248.

**Comment by agoldenberg01** [comment]
Hi bonigarcia:
Thank you very much for the suggestion and details of 318#issuecomment-472926248.
But, in my opinion,  I have a  different issue: the moment I have replaced the webdriver binary (from the latest 74.x to 73.x) the code (TestNG + Selenium) is working properly locally (launched from Eclipse - project xml file) without any problems.
The issue comes up whenever I need to run the same suite from Jenkins (our version is 2.153) job (Jenkins slave has been setup on that AWS Window 2012 image).
In this case I'm getting the error  - Exception org.openqa.selenium.remote.UnreachableBrowserException - and could be a lot if test cases have failed because of that and, actually, it crashes Chrome  - I can see it complains about improper previously closed issue when need to launch it manually.
Message: Error communicating with the remote browser. It may have died.
The WebDriverManager (https://www.toolsqa.com/selenium-webdriver/webdrivermanager/) allows dynamically to select and define proper webdriver compatible with the current version of a browser and doesn't interfere with Jenkins.
Please, advise.

Thanks a lot!

**Comment by bonigarcia** [comment]
I still think the same. I would not manipulate the driver binaries within their folders. If you are willing to do that, simply stop using WebDriverManager and handle chromedriver by yourself.

Your problem seems to be related with incompatible versions between Chrome and chromedriver. If you still want to do use WebDriverManager, I first would clear the cache (i.e. the folder where WebDriverManager stores the binaries, by default `~/.m2/repository/webdriver`) to start from a fresh cache. This can be done manually, simple removing that folder, and as of version 3.4.0 (just released), this can be done invoking the method `clearCache()` (e.g. `WebDriverManager.chromedriver().clearCache()`). Then, I would use the latest version of WebDriverManager, i.e. 3.4.0, which logs more information about the version of the driver (i.e. chromedriver) for the browser (Chrome).

If the problem is still happening, I would force the required version of the driver. If your Chrome is 73, then the proper chromedriver is 73.0.3683.68:

```
WebDriverManager.chromedriver().version("73.0.3683.68").setup();
```

**Comment by agoldenberg01** [comment]
Hi bonigarcia:
Thank you very much for the proper advice and latest 3.4.0 version of WebDriverManager, I have implemented it and it has been working properly.
The only thing I would like to discuss with you, if possible, the Jenkins job execution and connection, whenever I've been running some suites longer than 10 min, for some reason I've been getting  - 'Error communicating with the remote browser. It may have died...' error message and the test cases have not been execution and skipped.
I appreciate very much f you could've had some advice on this case also.
Thanks a lot!

**Comment by bonigarcia** [comment]
That problem is not related with WebDriverManager.

**Comment by SathishKumarBackiam** [comment]
Getting the below error when executing from Jenkins, however working fine in local. Could you please help regarding this.
Starting ChromeDriver 75.0.3770.90 (a6dcaf7e3ec6f70a194cc25e8149475c6590e025-refs/branch-heads/3770@{#1003}) on port 15307
Only local connections are allowed.
Please protect ports used by ChromeDriver and related test frameworks to prevent access by malicious code.
