### ISSUE TITLE
Prefs Error

### ISSUE THREAD

**Issue by Chazza** [bonigarcia/webdrivermanager#330]
Hi,

When launching FirefoxDriver with WebDriverManager I get:
```
Apr 21, 2019 8:35:54 PM java.util.prefs.WindowsPreferences <init>
WARNING: Could not open/create prefs root node Software\JavaSoft\Prefs at root 0x80000002. Windows RegCreateKeyEx(...) returned error code 5.
Apr 21, 2019 8:35:59 PM org.openqa.selenium.remote.ProtocolHandshake createSession
INFO: Detected dialect: W3C
```

Any reason why, and how would I get rid of these?

Thanks

**Comment by bonigarcia** [comment]
WebDriverManager 3.4.0 internally  use Java preferences to store resolved driver versions. Due to a known bug in Java under Windows, that warning appears. See [this](https://stackoverflow.com/questions/16428098/groovy-shell-warning-could-not-open-create-prefs-root-node) or [this](https://stackoverflow.com/questions/23720446/java-could-not-open-create-prefs-error).
