### ISSUE TITLE
Firefox 47 does not start

### ISSUE THREAD

**Issue by zeitalexgithub** [bonigarcia/webdrivermanager#35]
Hi
just got Firefox upgraded to 47 and my Selenium Test stoped working with FirefoxDriver and selenium-server-standalone.
I tried using WebDriver like this:
`System.setProperty("webdriver.gecko.driver", "C:\\path\\geckodriver.exe");
MarionetteDriverManager.getInstance().setup();
driver = new MarionetteDriver();`
my system:
- Win 7 64 bit
- webdrivermanager1.4.4.jar  (unfortunately we can not use maven)
- geckodriver-v0.8.0-win32

I can not find webdrivermanager1.4.5.jar and geckodriver-v0.8.0-win64

Any help will be highly appreciated
Alex

**Comment by bonigarcia** [comment]
Try with WebDriverManager version 1.4.5 which is available on [Maven Central](http://search.maven.org/#search%7Cgav%7C1%7Cg%3A%22io.github.bonigarcia%22%20AND%20a%3A%22webdrivermanager%22) (link to the jar [here](http://search.maven.org/remotecontent?filepath=io/github/bonigarcia/webdrivermanager/1.4.5/webdrivermanager-1.4.5.jar)).

**Comment by zeitalexgithub** [comment]
I am new to Selenium so it could be simple beginner problem

**Comment by jamiejackson** [comment]
I have a problem with geckodriver that seems similar:

`C:\Users\15037\.m2\repository\webdriver\geckodriver\win32\0.8.0\geckodriver.exe -b "C:\Program Files (x86)\Mozilla Firefox\firefox.exe"`

Gives: `The application was unable to start correctly (0x000007b). Click OK to close the application.`

Same thing happens when I directly download the driver from here: https://github.com/mozilla/geckodriver/releases (`geckodriver-v0.8.0-win32.zip`).

I'm new to the whole WebDriver universe, but [this](https://github.com/mozilla/geckodriver#usage) would seem to suggest that the command I tried should work.

**Comment by jamiejackson** [comment]
@zeitalexgithub, I believe you need to install `vc_redist.x86.exe` from the (https://www.microsoft.com/en-us/download/details.aspx?id=48145)[MS] site.

More info here: https://github.com/mozilla/geckodriver/issues/74#issuecomment-224621051

This seemed to fix it for me.

**Comment by zeitalexgithub** [comment]
Hi Jamie,
Thanks a lot for your answer. I installed vc_redist.x86.exe
Now after starting  geckodriver.exe -b "C:\Program Files\Mozilla
Firefox\firefox.exe"
it is still failing to start and I am getting:
thread '<main>' panicked at 'called `Result::unwrap()` on an `Err` value:
Io(Error { repr: Os { code: 10013, message: "Der Zugriff auf einen Socket
war aufgrund der Zugriffsrechte des Sockets unzul\u{e4}ssig." } })',
../src/libcore\result.rs:746


2016-06-13 21:37 GMT+02:00 Jamie Jackson <notifications@github.com>:

**Comment by jamiejackson** [comment]
@zeitalexgithub: Darn, an arcane rust-url error that I know even less about.
