### ISSUE TITLE
How to change the capabilities values?

### ISSUE THREAD

**Issue by alvaroGar** [bonigarcia/webdrivermanager#37]
How can I change the capabilities values when creating the driver?. I need to set acceptSslCerts=true

Thanks in advance for your help.

**Comment by bonigarcia** [comment]
I'm not sure. Take a look to [this](http://stackoverflow.com/questions/19975927/webdriver-ssl-certificate-accepting-not-working-on-sub-domain) or [this](http://stackoverflow.com/questions/5933871/handling-untrustedsslcertificates-using-webdriver). Nevertheless, if you are using Marionette, I'm afraid you are not going to be able to test web applications which use untrusted certificates (e.g. self-signed) because this is not supported yet (more info [here](https://bugzilla.mozilla.org/show_bug.cgi?id=1103196) and [here](https://wiki.mozilla.org/Auto-tools/Projects/Marionette/Auto-tools/Projects/Marionette/Roadmap)).

**Comment by alvaroGar** [comment]
Thanks for your answer, I will check your recommendations.
