### ISSUE TITLE
download not working when behind a Proxy

### ISSUE THREAD

**Issue by toschder** [bonigarcia/webdrivermanager#40]
I want to use PhantomJSDriver for my tests, so i tried a setup like this:
`PhantomJsDriverManager.getInstance().setup()`

For downloading, it internally uses HtmlUnitDriver - without a proxy being set:

```
PhantomJsDriverManager.getDrivers() 
...
// Using HtmlUnitDriver to read package URL
             WebDriver driver = new HtmlUnitDriver();
             driver.manage().timeouts().implicitlyWait(
                           WdmConfig.getInt("wdm.timeout"), TimeUnit.SECONDS);
             driver.get(phantomjsDriverUrl);
             WebElement downloadsTable = driver
                           .findElement(By.id("available-downloads"));

```
=> please add the option to setup a proxy here, so downloading the binaries will also work in a network behind a proxy.

**Comment by connor-hendrix** [comment]
@toschder Encountered the same issue due to my corporate proxy. 

A quick fix that I did was to manually set the proxy settings at the System level.

So for example:
`       System.setProperty("http.proxyHost", your.proxy.here");
        System.setProperty("http.proxyPort", "8080");

        ChromeDriverManager.getInstance().setup();`

**Comment by bonigarcia** [comment]
This issue is the same than #27.

I think the solution proposed by @connor-hendrix is a good fix.

**Comment by connor-hendrix** [comment]
@bonigarcia Figured it was better to set the proxy that way versus having to set it per connection.

**Comment by andref** [comment]
Well, the workaround proposed by @connor-hendrix does not work for the PhantomJS driver because its [`getDrivers`](https://github.com/bonigarcia/webdrivermanager/blob/webdrivermanager-1.4.8/src/main/java/io/github/bonigarcia/wdm/PhantomJsDriverManager.java#L68-L71) method uses the `HtmlUnitDriver` to fetch the download URLs:

```java
		// Using HtmlUnitDriver to read package URL
		WebDriver driver = new HtmlUnitDriver();
		driver.manage().timeouts().implicitlyWait(
				WdmConfig.getInt("wdm.timeout"), TimeUnit.SECONDS);
		driver.get(phantomjsDriverUrl);
		WebElement downloadsTable = driver
				.findElement(By.id("uploaded-files"));
```

The `HtmlUnitDriver` needs explicit proxy configuration, or it will try direct connections.

The other drivers just return a list of URLs that are then downloaded using the `Downloader` class which itself uses `URL.openConnection` which, as expected, reads the proxy configuration from the system properties.

**Comment by bonigarcia** [comment]
New version of WebDriverManager (1.4.9) get rids of HtmlUnit by downloading PhantomJs binaries from a [mirror](https://npm.taobao.org/mirrors/phantomjs/). This issue should be solved now.
