### ISSUE TITLE
Request for a new release version for maven

### ISSUE THREAD

**Issue by aji4032** [bonigarcia/webdrivermanager#441]
Hi,
Can i request for a new version of release please? I am using this dependency in one of my projects and noticed that chrome tests are still running on old chromedriver and that the release hasn't been updated since a while.

Thanks,
Aji

P.S.: I need not mention this as I guess everyone already knows this - this is a must have dependency for all if they are using selenium webdrivers! Thanks!. :)

**Comment by bonigarcia** [comment]
As explained in the doc:

_The relationship between browser version and driver version is managed in a internal database by WebDriverManager stored as Java properties in the file [versions.properties]. This file is maintained updated when a new driver or browser version is released. To use always the latest relationships between browser and driver, and due to its rapid change, the online version of [versions.properties] (master branch) is used._

Therefore, WebDriverManager updates automatically the version to use, and there is no need to a new version in Maven.
