### ISSUE TITLE
Support for Brave Browser

### ISSUE THREAD

**Issue by xbotuk** [bonigarcia/webdrivermanager#622]
Can you please add support for Brave Browser https://brave.com/download/

As it is based on Chromium, in theory it should work.

Thanks

**Comment by bonigarcia** [comment]
Since this browser is based on Chromium, the required driver should be `chromedriver`, and you can resolve it simply using the its manager. If you want to detect automatically the Brave version, as of WebDriverManager 4.4.0, you can use the method `browserVersionDetectionCommand()` to specify which command should be used to detect it. As follows:

        WebDriverManager.chromedriver().browserVersionDetectionCommand("/path/to/brave --version").setup();

**Comment by swapnilgawali14** [comment]
not able to setup the brave browser getting error to this line if code :
"The method browserVersionDetectionCommand(String) is undefined for the type WebDriverManager ""
