### ISSUE TITLE
Not able to launch chrome browser using webdriver manager

### ISSUE THREAD

**Issue by ffvfmy** [bonigarcia/webdrivermanager#79]
Hi I have a maven project where i am trying to launch chrome browser using webdrivermanager. Facing the below error in "ChromeDriverManager.getInstance().setup();" line
**Error:** Exception in thread "main" java.lang.NoClassDefFoundError: Could not initialize class io.github.bonigarcia.wdm.ChromeDriverManager

Here is what i tried:
Added the dependency to my pom:
<dependency>
    <groupId>io.github.bonigarcia</groupId>
    <artifactId>webdrivermanager</artifactId>
    <version>1.4.10</version>
</dependency>

Added the below line to launch chrome driver,
ChromeDriverManager.getInstance().setup();
driver = new ChromeDriver();

**Comment by bonigarcia** [comment]
I am not able to reproduce your problem. I made some tests and the manger for the Chrome binary (`ChromeDriverManager`) seems to work perfectly.

I have created a new repository with running examples of WebDriverManager: [webdrivermanager-examples](https://github.com/bonigarcia/webdrivermanager-examples). You can clone this repo and execute this test: [ChromeTest](https://github.com/bonigarcia/webdrivermanager-examples/blob/master/src/test/java/io/github/bonigarcia/wdm/test/ChromeTest.java).

In addition a new version of WebDriverManager has recently release: 1.5.0.

**Comment by shyamrock** [comment]
Hi
I get this error running the webdrivermanager-examples.  Can you shed some light on this:

Oct 04, 2017 6:17:43 PM org.openqa.selenium.os.UnixProcess checkForError

SEVERE: org.apache.commons.exec.ExecuteException: Execution failed (Exit value: -559038737. Caused by java.io.IOException: Cannot run program "C:\user\.m2\repository\webdriver\chromedriver\win32\2.33\chromedriver_win32.zip" (in directory "."): CreateProcess error=193, %1 is not a valid Win32 application)

**Comment by ranjith36** [comment]
@shyamrock I've faced the similar issue! but not sure it's the same for you anyway solution that worked for me is: https://www.centos.org/forums/viewtopic.php?t=60908&start=10
