### ISSUE TITLE
wdm does ignore application.properties

### ISSUE THREAD

**Issue by hennr** [bonigarcia/webdrivermanager#97]
Hi,

WDM does not honor the application.properties anymore in 1.5.0 since https://github.com/bonigarcia/webdrivermanager/commit/29c531266c78399f3999b246da479163d734bee8

This is a breaking change.

Is it a bug or was it done by intention? In the latter case it should have gone into the changelog and the README.md needs an update.

**Comment by bonigarcia** [comment]
Yes, it was an intentional change. This was done due to the fact that the name "application.properties" is too broad and it was causing problems to some users (see #72).

But you are right that I forgot to add this change in the changelog. I've just added it in a new [patch](https://github.com/bonigarcia/webdrivermanager/commit/c5f14a5ba7dce847efa06cd03dc253b91e7fcd95).
